# Settings file

# --- Rendering ---
renderDistance 3000
chunkSize 512
chunkResolution 45
enableDRS false
targetFPS 60
renderScale 0.8
enableFSR true
enableSSAO false
maxMipLevels 0
vsync false
frameCap 0
anisotropicFiltering false
maxAnisotropy 1
antiAliasingMode 0
msaaSamples 1
framesInFlight 3

# --- World & LOD Distances ---
fogStartRatio 0.8
fogEndRatio 1
staticFadeStartRatio 0.15
staticFadeEndRatio 0.2
grassFadeStartRatio 0.1
grassFadeEndRatio 0.2
terrainLod0EndRatio 0.25
terrainLod1EndRatio 0.4
terrainLod2EndRatio 0.7
terrainLod3EndRatio 0.8
enableMotionBlur false
enableGodRays false

# --- Debug ---
showStats true
timeScale 2

# --- Window ---
windowWidth 1280
windowHeight 720
fullscreen false
